import { Goal } from '../../../../core/domain/entities/goal/Goal';
import { GoalType } from '../../../../types/goal';

export class GoalMapper {
  toApiResponse(goal: Goal): { id: string; type: GoalType; targetValue: number; deadline: Date; progress: number; createdAt: Date; updatedAt: Date } {
    return {
      id: goal.id,
      type: goal.type,
      targetValue: goal.targetValue,
      deadline: goal.deadline,
      progress: goal.progress,
      createdAt: goal.createdAt,
      updatedAt: goal.updatedAt,
    };
  }

  toDomainObject(goalData: { type: GoalType; targetValue: number; deadline: Date; userId: string }): Goal {
    return {
      id: '', // Will be generated by the repository
      ...goalData,
      progress: 0, // Initial progress is 0
      createdAt: new Date(),
      updatedAt: new Date(),
    };
  }
}